[package]
name = "assembler"
version = "0.1.0"
authors = ["Jiří Šebele <sindriava@gmail.com>"]
build = "build.rs"

[dependencies]
clap = "*"
lazy_static = "1.0.0"

serde = "*"
serde_json = "*"

[build-dependencies]
peg = "*"
